# Framing (Section 5.2)
LENGTH_PREFIX_BYTES = 4 # 4-byte big-endian unsigned length prefix
LENGTH_BYTEORDER = "big"
MAX_PDU_SIZE_BYTES = 65_535 # RFC hard cap on JSON payload size

PORT = 4444

# PDU type strings (Section 10.1)
# Lobby / session lifecycle
PLAYER_READY = "PLAYER_READY"
GAME_STATE_UPDATE = "GAME_STATE_UPDATE"

# Setup / mulligan
MULLIGAN_CHOICE = "MULLIGAN_CHOICE"

# Turn / phase flow control
PHASE_TRANSITION = "PHASE_TRANSITION"

# Priority & the stack
PRIORITY_GRANT = "PRIORITY_GRANT"
PRIORITY_PASS = "PRIORITY_PASS"
CAST_SPELL = "CAST_SPELL"
ACTIVATE_ABILITY = "ACTIVATE_ABILITY"
STACK_PUSH = "STACK_PUSH"
STACK_RESOLVE = "STACK_RESOLVE"
TRIGGER_ORDER = "TRIGGER_ORDER"
TRIGGER_ORDER_RESPONSE = "TRIGGER_ORDER_RESPONSE"
TRIGGER_CHOICE = "TRIGGER_CHOICE"
TRIGGER_CHOICE_RESPONSE = "TRIGGER_CHOICE_RESPONSE"

# Combat sub-phase actions
DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
COMBAT_DAMAGE_RESULT = "COMBAT_DAMAGE_RESULT"

# Player actions outside the stack
PLAY_LAND = "PLAY_LAND"
DISCARD = "DISCARD"

# Session-ending / meta
CONCEDE = "CONCEDE"
GAME_OVER = "GAME_OVER"

# Connection health / errors
PING = "PING"
PONG = "PONG"
ERROR = "ERROR"

ALL_PDU_TYPES = frozenset({
    PLAYER_READY, GAME_STATE_UPDATE, MULLIGAN_CHOICE, PHASE_TRANSITION,
    PRIORITY_GRANT, PRIORITY_PASS, CAST_SPELL, ACTIVATE_ABILITY,
    STACK_PUSH, STACK_RESOLVE, TRIGGER_ORDER, TRIGGER_ORDER_RESPONSE,
    TRIGGER_CHOICE, TRIGGER_CHOICE_RESPONSE, DECLARE_ATTACKERS,
    DECLARE_BLOCKERS, ASSIGN_DAMAGE_ORDER, COMBAT_DAMAGE_RESULT,
    PLAY_LAND, DISCARD, CONCEDE, GAME_OVER, PING, PONG, ERROR,
})

# PDU types that are exempt from the "echo the last priority-bearing
# seq_num" rule (Section 5.4). CONCEDE and PING keep their own counters.
SEQ_NUM_EXEMPT_TYPES = frozenset({CONCEDE, PING})

# Game lifecycle states (Section 6.1)
STATE_LOBBY = "LOBBY"
STATE_GAME_SETUP = "GAME_SETUP"
STATE_MULLIGAN = "MULLIGAN"
STATE_IN_GAME = "IN_GAME"
STATE_GAME_OVER = "GAME_OVER"

# Turn phases / steps (Section 10.2.4)
PHASE_UNTAP = "UNTAP"
PHASE_UPKEEP = "UPKEEP"
PHASE_DRAW = "DRAW"
PHASE_PRECOMBAT_MAIN = "PRECOMBAT_MAIN"
PHASE_BEGIN_COMBAT = "BEGIN_COMBAT"
PHASE_DECLARE_ATTACKERS = "DECLARE_ATTACKERS"
PHASE_DECLARE_BLOCKERS = "DECLARE_BLOCKERS"
PHASE_ASSIGN_DAMAGE_ORDER = "ASSIGN_DAMAGE_ORDER"
PHASE_FIRST_STRIKE_DAMAGE = "FIRST_STRIKE_DAMAGE"
PHASE_COMBAT_DAMAGE = "COMBAT_DAMAGE"
PHASE_END_OF_COMBAT = "END_OF_COMBAT"
PHASE_POSTCOMBAT_MAIN = "POSTCOMBAT_MAIN"
PHASE_END_STEP = "END_STEP"
PHASE_CLEANUP = "CLEANUP"

# Ordered tuple - index order matches turn sequence (Section 7.1 / Fig. 4)
PHASE_ORDER = (
    PHASE_UNTAP, PHASE_UPKEEP, PHASE_DRAW, PHASE_PRECOMBAT_MAIN,
    PHASE_BEGIN_COMBAT, PHASE_DECLARE_ATTACKERS, PHASE_DECLARE_BLOCKERS,
    PHASE_ASSIGN_DAMAGE_ORDER, PHASE_FIRST_STRIKE_DAMAGE, PHASE_COMBAT_DAMAGE,
    PHASE_END_OF_COMBAT, PHASE_POSTCOMBAT_MAIN, PHASE_END_STEP, PHASE_CLEANUP,
)

# Steps that open a priority window (Section 7.1 marks these explicitly)
PRIORITY_WINDOW_PHASES = frozenset({
    PHASE_UPKEEP, PHASE_DRAW, PHASE_PRECOMBAT_MAIN, PHASE_BEGIN_COMBAT,
    PHASE_DECLARE_ATTACKERS, PHASE_DECLARE_BLOCKERS, PHASE_ASSIGN_DAMAGE_ORDER,
    PHASE_FIRST_STRIKE_DAMAGE, PHASE_COMBAT_DAMAGE, PHASE_END_OF_COMBAT,
    PHASE_POSTCOMBAT_MAIN, PHASE_END_STEP,
})

# Stack item types (Section 8.3)
ITEM_TYPE_SPELL = "SPELL"
ITEM_TYPE_ABILITY = "ABILITY"
ITEM_TYPE_TRIGGER_ABILITY = "TRIGGER_ABILITY"

STACK_ITEM_TYPES = frozenset({
    ITEM_TYPE_SPELL, ITEM_TYPE_ABILITY, ITEM_TYPE_TRIGGER_ABILITY,
})

# Stack resolution results (Section 8.4 / 10.2.14)
RESULT_RESOLVED = "RESOLVED"
RESULT_FIZZLE = "FIZZLE"
STACK_RESOLVE_RESULTS = frozenset({RESULT_RESOLVED, RESULT_FIZZLE})

# GAME_OVER reasons (Section 6.6 / 10.2.22)
REASON_LIFE_ZERO = "LIFE_ZERO"
REASON_DECK_EMPTY = "DECK_EMPTY"
REASON_CONCEDE = "CONCEDE"
REASON_DISCONNECT = "DISCONNECT"

GAME_OVER_REASONS = frozenset({
    REASON_LIFE_ZERO, REASON_DECK_EMPTY, REASON_CONCEDE, REASON_DISCONNECT,
})

# Mana colors (Section 10.2.7)
MANA_WHITE = "W"
MANA_BLUE = "U"
MANA_BLACK = "B"
MANA_RED = "R"
MANA_GREEN = "G"
MANA_GENERIC = "X"

MANA_COLORS = frozenset({
    MANA_WHITE, MANA_BLUE, MANA_BLACK, MANA_RED, MANA_GREEN, MANA_GENERIC,
})

# Error codes (Section 11)
ERR_INVALID_JSON = "INVALID_JSON"
ERR_ILLEGAL_DECK = "ILLEGAL_DECK"
ERR_UNKNOWN_TYPE = "UNKNOWN_TYPE"
ERR_STALE_ACTION = "STALE_ACTION"
ERR_NOT_YOUR_PRIORITY = "NOT_YOUR_PRIORITY"
ERR_ILLEGAL_ACTION = "ILLEGAL_ACTION"
ERR_ILLEGAL_TARGET = "ILLEGAL_TARGET"
ERR_TRIGGER_ORDER_INVALID = "TRIGGER_ORDER_INVALID"
ERR_TRIGGER_CHOICE_INVALID = "TRIGGER_CHOICE_INVALID"
ERR_INSUFFICIENT_MANA = "INSUFFICIENT_MANA"
ERR_WRONG_PHASE = "WRONG_PHASE"
ERR_DUPLICATE_ID = "DUPLICATE_ID"

ERROR_CODES = frozenset({
    ERR_INVALID_JSON, ERR_ILLEGAL_DECK, ERR_UNKNOWN_TYPE, ERR_STALE_ACTION,
    ERR_NOT_YOUR_PRIORITY, ERR_ILLEGAL_ACTION, ERR_ILLEGAL_TARGET,
    ERR_TRIGGER_ORDER_INVALID, ERR_TRIGGER_CHOICE_INVALID,
    ERR_INSUFFICIENT_MANA, ERR_WRONG_PHASE, ERR_DUPLICATE_ID,
})

# Deck / hand rules (Section 6.3)
MIN_DECK_SIZE = 1
MAX_DECK_SIZE = 50
STARTING_LIFE_TOTAL = 20
STARTING_HAND_SIZE = 7
MAX_HAND_SIZE = 7  # cleanup discard trigger threshold

# Timing (Section 4.2 / 4.3, RECOMMENDED values)
DEFAULT_TIME_LIMIT_MS = 60_000
RECOMMENDED_PING_INTERVAL_S = 30
RECOMMENDED_PONG_TIMEOUT_S = 10
